"""Public domain types for the frozen spec-v1 model."""

from .anomaly_record import (
    AnomalyContribution,
    AnomalyCritCapability,
    AnomalyEffectStrengthTrace,
    AnomalyRecord,
    AnomalyStrengthFactor,
    IndependentAnomalyCrit,
    NoAnomalyCrit,
)
from .anomaly_gauge import (
    AnomalyBuildupApplicationContext,
    AnomalyGauge,
    AnomalyGaugeApplication,
    AnomalyTriggerSnapshot,
)
from .battle_state import BattleState, CharacterCombatState, EnemyCombatState
from .build import (
    BuildContributionLayer,
    BuildContributionTrace,
    BuildMode,
    BuildSource,
    BuildSourceType,
    BuildStatContribution,
    CharacterBuildDefinition,
)
from .battle_event import (
    AnomalyBuildupEvent,
    AnomalyBuildupOutcome,
    BattleEvent,
    BattleEventMetadata,
    BattleEventOutcome,
    BattleEventResult,
    DamageEventOutcome,
    DazeEvent,
    DazeOutcome,
    EventCreationOutcome,
    OutcomeDependency,
    ResourceChangeOutcome,
    SkillHitEvent,
    StateChangeOutcome,
)
from .calculation_context import (
    CalculationContext,
    CharacterSnapshot,
    EnemySnapshot,
    InitialCharacterSnapshot,
    Modifier,
)
from .calculation_node import CalculationNode
from .character import Character, CharacterPanelLayers, CharacterStats
from .common import (
    AnomalyRecordId,
    BattleEnvironmentRef,
    BattleEventId,
    BattleOutcomeId,
    BattleStateId,
    BattleTime,
    CharacterId,
    CharacterRef,
    DamageEventId,
    DriveDiscSetId,
    EffectId,
    EnemyId,
    EnemyRef,
    EntityRef,
    EventTemplateId,
    HitId,
    MoveId,
    Multiplier,
    Ratio,
    Resolvable,
    Resolved,
    ResourceId,
    RuleSourceId,
    Seconds,
    StateId,
    Unresolved,
    UnresolvedReason,
    WEngineId,
)
from .damage_event import (
    AnomalyRecordValueField,
    AnomalyRecordValueSource,
    AttributeAnomalyDamageEvent,
    BaseSettlementDataSource,
    CalculationNodeMultiplier,
    CritRule,
    CurrentAttackValueSource,
    CurrentAnomalyEffectStrengthValueSource,
    CurrentAnomalyProficiencyValueSource,
    CurrentPenetrationForceValueSource,
    DamageEvent,
    DamageEventMetadata,
    DamageMultiplier,
    DirectDamageEvent,
    CurrentAttributeAnomalyDamageEvent,
    SettledAnomalyDamageEvent,
    SettledDamageValueSource,
    DischargeDamageEvent,
    DisorderDamageEvent,
    FixedMultiplier,
    IndependentAnomalyCritRule,
    LuminanceDamageEvent,
    NoCritRule,
    PenetrationDamageEvent,
    RecordedAnomalyCritRule,
    StandardCritRule,
    TurbulenceDamageEvent,
    UnresolvedSharpExplosionDamageEvent,
)
from .effect import (
    AllCondition,
    AlwaysCondition,
    AnyCondition,
    AnyFilter,
    CharacterFilter,
    CharacterRoleFilter,
    CreatedByEffectFilter,
    Condition,
    DamageSubtypeFilter,
    DamageTagFilter,
    DamageTypeFilter,
    DamageDealerFilter,
    DynamicIdentityCondition,
    DynamicIdentityFilter,
    Effect,
    EffectFilter,
    EffectRule,
    ElementFilter,
    EnemyStateFilter,
    EventCreationEffect,
    EventCreationResult,
    EventSelector,
    FieldPositionFilter,
    ModifierEffect,
    ModifierResult,
    ModifierValue,
    MoveIdFilter,
    NotCondition,
    NotFilter,
    OperationStateFilter,
    PanelStatDerivedValue,
    ScenarioParameterDerivedValue,
    PanelStatThresholdCondition,
    RuleStackCondition,
    SkillGroupFilter,
    StateChangeEffect,
    StateChangeResult,
    StatePresentCondition,
    UnresolvedEffect,
)
from .enemy import Enemy
from .enums import (
    ANOMALY_DAMAGE_KIND_BY_ELEMENT,
    ANOMALY_ELEMENTS,
    ANOMALY_STATE_KIND_BY_ELEMENT,
    BASE_ELEMENT_BY_ELEMENT,
    AttributeAnomalyDamageKind,
    AttributeAnomalyStateKind,
    BattleEventKind,
    CharacterRole,
    CharacterStat,
    DamageSubtype,
    DamageTag,
    DamageType,
    DynamicIdentity,
    EffectOperation,
    EffectSourceType,
    EffectTarget,
    Element,
    FieldPosition,
    OperationState,
    ResourceKind,
    SkillGroup,
    SnapshotRule,
    StateChangeAction,
    StateKind,
)
from .source import RuleSource
from .state import Duration, StackingRule, State, TimedDuration, UntilEventDuration
from .vulnerability import (
    StandardVulnerabilityPolicy,
    VeilVulnerabilityPolicy,
    VulnerabilitySettlementPolicy,
)
from .wengine import EquipmentOwnerCapabilities, WEngineBuildInput
from .drive_disc import (
    DRIVE_DISC_MAIN_STATS_BY_SLOT,
    DRIVE_DISC_MAIN_STAT_VALUES,
    DRIVE_DISC_SUBSTAT_VALUES,
    DriveDiscBuildInput,
    DriveDiscSlot,
    DriveDiscStatKey,
    DriveDiscSubstatRoll,
    EquippedDriveDisc,
)
