"""Stable IDs for the reviewed W-Engine slices."""

from core.types import CharacterId, WEngineId


WENGINE_ASTRA_ID = WEngineId("wengine:14131")
WENGINE_LUNAR_PLENILUNA_ID = WEngineId("wengine:12001")
WENGINE_LUNAR_DECRESCENT_ID = WEngineId("wengine:12002")
WENGINE_LUNAR_NOVILUNA_ID = WEngineId("wengine:12003")
WENGINE_REVERB_MARK_I_ID = WEngineId("wengine:12004")
WENGINE_REVERB_MARK_II_ID = WEngineId("wengine:12005")
WENGINE_YE_ID = WEngineId("wengine:14143")
WENGINE_TURBULENCE_CANNON_ID = WEngineId("wengine:12007")
WENGINE_TURBULENCE_ARROW_ID = WEngineId("wengine:12008")
WENGINE_TURBULENCE_AXE_ID = WEngineId("wengine:12009")
WENGINE_ELECTRO_STORM_I_ID = WEngineId("wengine:12010")
WENGINE_ELECTRO_STORM_II_ID = WEngineId("wengine:12011")
WENGINE_ELECTRO_STORM_III_ID = WEngineId("wengine:12012")
WENGINE_IDENTITY_STANDARD_ID = WEngineId("wengine:12013")
WENGINE_IDENTITY_ALTERNATE_ID = WEngineId("wengine:12014")
WENGINE_ASH_COBALT_BLUE_ID = WEngineId("wengine:12015")
WENGINE_LUNAR_STRING_ID = WEngineId("wengine:12016")
WENGINE_STREET_SUPERSTAR_ID = WEngineId("wengine:13001")
WENGINE_TIME_SLICE_ID = WEngineId("wengine:13002")
WENGINE_RAINFOREST_GOURMAND_ID = WEngineId("wengine:13003")
WENGINE_STARLIGHT_ENGINE_ID = WEngineId("wengine:13004")
WENGINE_HUMAN_IS_MEAT_ID = WEngineId("wengine:13005")
WENGINE_REEL_PROJECTOR_ID = WEngineId("wengine:13016")
WENGINE_CATTY_LUCK_ID = WEngineId("wengine:13017")
WENGINE_BOISTEROUS_ECHOES_ID = WEngineId("wengine:13018")
WENGINE_CAULDRON_OF_CLARITY_ID = WEngineId("wengine:13019")
WENGINE_SIMMERING_POT_ID = WEngineId("wengine:13020")
WENGINE_BLOODMARROW_COFFER_ID = WEngineId("wengine:13021")
WENGINE_DEMARA_BATTERY_II_ID = WEngineId("wengine:13101")
WENGINE_HOUSEKEEPER_ID = WEngineId("wengine:13106")
WENGINE_STARLIGHT_ENGINE_REPLICA_ID = WEngineId("wengine:13108")
WENGINE_DRILL_RIG_RED_AXIS_ID = WEngineId("wengine:13111")
WENGINE_BIG_CYLINDER_ID = WEngineId("wengine:13112")
WENGINE_BASHFUL_DEMON_ID = WEngineId("wengine:13113")
WENGINE_KABOOM_THE_CANNON_ID = WEngineId("wengine:13115")
WENGINE_PEACEKEEPER_SPECIALIZED_ID = WEngineId("wengine:13127")
WENGINE_ROARING_RIDE_ID = WEngineId("wengine:13128")
WENGINE_BOX_CUTTER_ID = WEngineId("wengine:13135")
WENGINE_TREMOR_TRIGRAM_VESSEL_ID = WEngineId("wengine:13142")
WENGINE_GRILL_O_WISP_ID = WEngineId("wengine:13144")
WENGINE_CANNON_ROTOR_ID = WEngineId("wengine:14001")
WENGINE_UNFETTERED_GAME_BALL_ID = WEngineId("wengine:14002")
WENGINE_SIX_SHOOTER_ID = WEngineId("wengine:14003")
WENGINE_KRAKENS_CRADLE_ID = WEngineId("wengine:14105")
WENGINE_TUSKS_OF_FURY_ID = WEngineId("wengine:14107")
WENGINE_HAILSTORM_SHRINE_ID = WEngineId("wengine:14109")
WENGINE_HELLFIRE_GEARS_ID = WEngineId("wengine:14110")
WENGINE_RESTRAINED_ID = WEngineId("wengine:14114")
WENGINE_BLAZING_LAUREL_ID = WEngineId("wengine:14116")
WENGINE_FLAMEMAKER_SHAKER_ID = WEngineId("wengine:14117")
WENGINE_FUSION_COMPILER_ID = WEngineId("wengine:14118")
WENGINE_TIMEWEAVER_ID = WEngineId("wengine:14122")
WENGINE_JADE_TEA_ID = WEngineId("wengine:14125")
WENGINE_STINGING_RAZOR_ID = WEngineId("wengine:14126")
WENGINE_SUNFALL_EDGE_ID = WEngineId("wengine:14129")
WENGINE_HELLHOUND_BOOMSTICK_ID = WEngineId("wengine:14130")
WENGINE_NIGHT_HARPS_ID = WEngineId("wengine:14132")
WENGINE_BIRD_DREAM_ID = WEngineId("wengine:14133")
WENGINE_SWEETBUNNY_ID = WEngineId("wengine:14134")
WENGINE_CYAN_CAGE_ID = WEngineId("wengine:14137")
WENGINE_FUYUAN_CLEAN_ID = WEngineId("wengine:14138")
WENGINE_FOX_FURNACE_ID = WEngineId("wengine:14139")
WENGINE_PRECISE_TRANSFORMER_ID = WEngineId("wengine:13007")
WENGINE_PRECIOUS_FOSSIL_ID = WEngineId("wengine:13006")
WENGINE_TWIN_CRYING_STARS_ID = WEngineId("wengine:13008")
WENGINE_ELECTRIC_LIP_GLOSS_ID = WEngineId("wengine:13009")
WENGINE_BUNNY_BAND_ID = WEngineId("wengine:13010")
WENGINE_SPRING_WARMTH_ID = WEngineId("wengine:13011")
WENGINE_FANTASY_CUBE_ID = WEngineId("wengine:13012")
WENGINE_GILDED_BLOSSOM_ID = WEngineId("wengine:13013")
WENGINE_RADIO_WAVE_WALK_ID = WEngineId("wengine:13014")
WENGINE_STRONG_ENOUGH_ID = WEngineId("wengine:13015")
WENGINE_STEEL_CUSHION_ID = WEngineId("wengine:14102")
WENGINE_BRIMSTONE_ID = WEngineId("wengine:14104")
WENGINE_DEEP_SEA_VISITOR_ID = WEngineId("wengine:14119")
WENGINE_HEART_OF_SWORD_ID = WEngineId("wengine:14120")
WENGINE_DEFENSE_PATROL_ID = WEngineId("wengine:14124")
WENGINE_RESONAB_THREE_ID = WEngineId("wengine:12006")
WENGINE_TREASURE_CHEST_ID = WEngineId("wengine:13103")
WENGINE_CRYING_CRADLE_ID = WEngineId("wengine:14121")
WENGINE_DREAM_FORGE_ID = WEngineId("wengine:14145")
WENGINE_SONG_OF_NOISE_ID = WEngineId("wengine:14149")
WENGINE_TRIGGER_ID = WEngineId("wengine:14136")
WENGINE_ALICE_ID = WEngineId("wengine:14140")
WENGINE_YUZUHA_ID = WEngineId("wengine:14141")
WENGINE_ATTACK_SAMPLE_IDS = (
    WENGINE_STEEL_CUSHION_ID,
    WENGINE_BRIMSTONE_ID,
    WENGINE_DEEP_SEA_VISITOR_ID,
    WENGINE_HEART_OF_SWORD_ID,
    WENGINE_DEFENSE_PATROL_ID,
)
WENGINE_SUPPORT_SAMPLE_IDS = (
    WENGINE_RESONAB_THREE_ID,
    WENGINE_TREASURE_CHEST_ID,
    WENGINE_CRYING_CRADLE_ID,
    WENGINE_DREAM_FORGE_ID,
    WENGINE_SONG_OF_NOISE_ID,
)
WENGINE_STAGE_18_2_5_IDS = WENGINE_ATTACK_SAMPLE_IDS + WENGINE_SUPPORT_SAMPLE_IDS
WENGINE_SIGNATURE_IDS = (
    WENGINE_TRIGGER_ID,
    WENGINE_ALICE_ID,
    WENGINE_YUZUHA_ID,
)
ASTRA_ID = CharacterId("character:1311")
YE_ID = CharacterId("character:1431")
ALICE_ID = CharacterId("character:1401")
YUZUHA_ID = CharacterId("character:1411")
TRIGGER_ID = CharacterId("character:1361")


__all__ = [
    "ASTRA_ID",
    "YE_ID",
    "ALICE_ID",
    "YUZUHA_ID",
    "TRIGGER_ID",
    "WENGINE_ASTRA_ID",
    "WENGINE_LUNAR_PLENILUNA_ID",
    "WENGINE_LUNAR_DECRESCENT_ID",
    "WENGINE_LUNAR_NOVILUNA_ID",
    "WENGINE_REVERB_MARK_I_ID",
    "WENGINE_REVERB_MARK_II_ID",
    "WENGINE_TURBULENCE_CANNON_ID",
    "WENGINE_TURBULENCE_ARROW_ID",
    "WENGINE_TURBULENCE_AXE_ID",
    "WENGINE_ELECTRO_STORM_I_ID",
    "WENGINE_ELECTRO_STORM_II_ID",
    "WENGINE_ELECTRO_STORM_III_ID",
    "WENGINE_IDENTITY_STANDARD_ID",
    "WENGINE_IDENTITY_ALTERNATE_ID",
    "WENGINE_ASH_COBALT_BLUE_ID",
    "WENGINE_LUNAR_STRING_ID",
    "WENGINE_STREET_SUPERSTAR_ID",
    "WENGINE_TIME_SLICE_ID",
    "WENGINE_RAINFOREST_GOURMAND_ID",
    "WENGINE_STARLIGHT_ENGINE_ID",
    "WENGINE_HUMAN_IS_MEAT_ID",
    "WENGINE_REEL_PROJECTOR_ID",
    "WENGINE_CATTY_LUCK_ID",
    "WENGINE_BOISTEROUS_ECHOES_ID",
    "WENGINE_CAULDRON_OF_CLARITY_ID",
    "WENGINE_SIMMERING_POT_ID",
    "WENGINE_BLOODMARROW_COFFER_ID",
    "WENGINE_DEMARA_BATTERY_II_ID",
    "WENGINE_HOUSEKEEPER_ID",
    "WENGINE_STARLIGHT_ENGINE_REPLICA_ID",
    "WENGINE_DRILL_RIG_RED_AXIS_ID",
    "WENGINE_BIG_CYLINDER_ID",
    "WENGINE_BASHFUL_DEMON_ID",
    "WENGINE_KABOOM_THE_CANNON_ID",
    "WENGINE_PEACEKEEPER_SPECIALIZED_ID",
    "WENGINE_ROARING_RIDE_ID",
    "WENGINE_BOX_CUTTER_ID",
    "WENGINE_TREMOR_TRIGRAM_VESSEL_ID",
    "WENGINE_GRILL_O_WISP_ID",
    "WENGINE_CANNON_ROTOR_ID",
    "WENGINE_UNFETTERED_GAME_BALL_ID",
    "WENGINE_SIX_SHOOTER_ID",
    "WENGINE_KRAKENS_CRADLE_ID",
    "WENGINE_TUSKS_OF_FURY_ID",
    "WENGINE_HAILSTORM_SHRINE_ID",
    "WENGINE_HELLFIRE_GEARS_ID",
    "WENGINE_RESTRAINED_ID",
    "WENGINE_BLAZING_LAUREL_ID",
    "WENGINE_FLAMEMAKER_SHAKER_ID",
    "WENGINE_FUSION_COMPILER_ID",
    "WENGINE_TIMEWEAVER_ID",
    "WENGINE_JADE_TEA_ID",
    "WENGINE_STINGING_RAZOR_ID",
    "WENGINE_SUNFALL_EDGE_ID",
    "WENGINE_HELLHOUND_BOOMSTICK_ID",
    "WENGINE_NIGHT_HARPS_ID",
    "WENGINE_BIRD_DREAM_ID",
    "WENGINE_SWEETBUNNY_ID",
    "WENGINE_CYAN_CAGE_ID",
    "WENGINE_FUYUAN_CLEAN_ID",
    "WENGINE_FOX_FURNACE_ID",
    "WENGINE_PRECISE_TRANSFORMER_ID",
    "WENGINE_PRECIOUS_FOSSIL_ID",
    "WENGINE_TWIN_CRYING_STARS_ID",
    "WENGINE_ELECTRIC_LIP_GLOSS_ID",
    "WENGINE_BUNNY_BAND_ID",
    "WENGINE_SPRING_WARMTH_ID",
    "WENGINE_FANTASY_CUBE_ID",
    "WENGINE_GILDED_BLOSSOM_ID",
    "WENGINE_RADIO_WAVE_WALK_ID",
    "WENGINE_STRONG_ENOUGH_ID",
    "WENGINE_YE_ID",
    "WENGINE_ATTACK_SAMPLE_IDS",
    "WENGINE_SUPPORT_SAMPLE_IDS",
    "WENGINE_STAGE_18_2_5_IDS",
    "WENGINE_SIGNATURE_IDS",
    "WENGINE_STEEL_CUSHION_ID",
    "WENGINE_BRIMSTONE_ID",
    "WENGINE_DEEP_SEA_VISITOR_ID",
    "WENGINE_HEART_OF_SWORD_ID",
    "WENGINE_DEFENSE_PATROL_ID",
    "WENGINE_RESONAB_THREE_ID",
    "WENGINE_TREASURE_CHEST_ID",
    "WENGINE_CRYING_CRADLE_ID",
    "WENGINE_DREAM_FORGE_ID",
    "WENGINE_SONG_OF_NOISE_ID",
    "WENGINE_TRIGGER_ID",
    "WENGINE_ALICE_ID",
    "WENGINE_YUZUHA_ID",
]
