"""Stable IDs for the reviewed W-Engine slices."""

from core.types import CharacterId, WEngineId


WENGINE_ASTRA_ID = WEngineId("wengine:14131")
WENGINE_YE_ID = WEngineId("wengine:14143")
WENGINE_STEEL_CUSHION_ID = WEngineId("wengine:14102")
WENGINE_BRIMSTONE_ID = WEngineId("wengine:14104")
WENGINE_DEEP_SEA_VISITOR_ID = WEngineId("wengine:14119")
WENGINE_HEART_OF_SWORD_ID = WEngineId("wengine:14120")
WENGINE_DEFENSE_PATROL_ID = WEngineId("wengine:14124")
WENGINE_RESONAB_THREE_ID = WEngineId("wengine:12006")
WENGINE_TREASURE_CHEST_ID = WEngineId("wengine:13103")
WENGINE_CRYING_CRADLE_ID = WEngineId("wengine:14121")
WENGINE_DREAM_FORGE_ID = WEngineId("wengine:14145")
WENGINE_SONG_OF_NOISE_ID = WEngineId("wengine:14149")
WENGINE_ATTACK_SAMPLE_IDS = (
    WENGINE_STEEL_CUSHION_ID,
    WENGINE_BRIMSTONE_ID,
    WENGINE_DEEP_SEA_VISITOR_ID,
    WENGINE_HEART_OF_SWORD_ID,
    WENGINE_DEFENSE_PATROL_ID,
)
WENGINE_SUPPORT_SAMPLE_IDS = (
    WENGINE_RESONAB_THREE_ID,
    WENGINE_TREASURE_CHEST_ID,
    WENGINE_CRYING_CRADLE_ID,
    WENGINE_DREAM_FORGE_ID,
    WENGINE_SONG_OF_NOISE_ID,
)
WENGINE_STAGE_18_2_5_IDS = WENGINE_ATTACK_SAMPLE_IDS + WENGINE_SUPPORT_SAMPLE_IDS
ASTRA_ID = CharacterId("character:1311")
YE_ID = CharacterId("character:1431")


__all__ = [
    "ASTRA_ID",
    "YE_ID",
    "WENGINE_ASTRA_ID",
    "WENGINE_YE_ID",
    "WENGINE_ATTACK_SAMPLE_IDS",
    "WENGINE_SUPPORT_SAMPLE_IDS",
    "WENGINE_STAGE_18_2_5_IDS",
    "WENGINE_STEEL_CUSHION_ID",
    "WENGINE_BRIMSTONE_ID",
    "WENGINE_DEEP_SEA_VISITOR_ID",
    "WENGINE_HEART_OF_SWORD_ID",
    "WENGINE_DEFENSE_PATROL_ID",
    "WENGINE_RESONAB_THREE_ID",
    "WENGINE_TREASURE_CHEST_ID",
    "WENGINE_CRYING_CRADLE_ID",
    "WENGINE_DREAM_FORGE_ID",
    "WENGINE_SONG_OF_NOISE_ID",
]
