"""Application contracts between parsed rules, scenarios, and calculators."""

from .diagnostics import CalculationDiagnostic, DiagnosticKind
from .build import ResolvedBuild, assemble_build
from .equipment import (
    DriveDiscBuildResolution,
    compile_drive_discs,
    stable_set_id,
    WEngineBuildResolution,
    WEngineRawRecord,
    SIGNATURE_WENGINE_BY_CHARACTER,
    compile_wengine,
    load_wengine_raw_record,
    signature_wengine_id_for,
    WEngineReviewedMapping,
    WENGINE_REVIEWED_MAPPINGS,
    reviewed_mapping_for,
)
from .element_scope import element_scope_filter
from .execution import (
    CalculationRouter,
    CalculatorExecutionResult,
    DamageEventExecutionTrace,
    DirectMoveApplicationService,
    EventStatModifier,
    InstantiatedDamageEvent,
    MatchedEffectApplication,
    ModifierApplicationResult,
    apply_global_panel_effects,
    MoveCalculationExecution,
    MoveCalculationRequest,
    PanelModifierExecutionTrace,
    MoveMultiplierResolution,
    MultiplierResolutionStatus,
    apply_matched_modifiers,
    calculate_move,
    instantiate_direct_damage_event,
    resolve_move_multiplier,
)
from .ids import (
    DiagnosticId,
    DamageEventSemanticId,
    MoveEntryId,
    MultiplierVariantId,
    RuleItemId,
    ScenarioConditionId,
    ScenarioParameterId,
)
from .moves import (
    DamageEventTemplateRef,
    DerivedDamageEventTemplateRef,
    MoveCalculationEntry,
    MultiplierRelation,
    MultiplierVariant,
)
from .output import (
    CritDisplayMode,
    DamageEventCalculationOutput,
    EventCalculationStatus,
    MoveCalculationOutput,
)
from .rules import CalculationRuleItem, RuleEligibility
from .scenario import (
    CalculationScenario,
    ConditionResolution,
    ParameterResolution,
    ScenarioCondition,
    ScenarioIntegerParameter,
    ScenarioRuleStack,
    ScenarioTriggerFact,
)
from .matching import (
    CharacterMatchProfile,
    DynamicIdentityResolver,
    EffectMatchContext,
    EffectMatchResult,
    EffectMatchStatus,
    EffectMatcher,
    EnemyMatchProfile,
    HistoryRecordResolution,
    IdentityResolution,
    RuleItemMatchResult,
    ScenarioTriggerFactView,
)

__all__ = [
    "CalculationDiagnostic",
    "ResolvedBuild",
    "DriveDiscBuildResolution",
    "assemble_build",
    "WEngineBuildResolution",
    "WEngineRawRecord",
    "SIGNATURE_WENGINE_BY_CHARACTER",
    "compile_wengine",
    "compile_drive_discs",
    "stable_set_id",
    "load_wengine_raw_record",
    "signature_wengine_id_for",
    "WEngineReviewedMapping",
    "WENGINE_REVIEWED_MAPPINGS",
    "reviewed_mapping_for",
    "CalculationRuleItem",
    "CalculationScenario",
    "CharacterMatchProfile",
    "ConditionResolution",
    "CritDisplayMode",
    "DamageEventCalculationOutput",
    "DamageEventTemplateRef",
    "DerivedDamageEventTemplateRef",
    "DiagnosticId",
    "DiagnosticKind",
    "DynamicIdentityResolver",
    "EventCalculationStatus",
    "DamageEventSemanticId",
    "MoveCalculationEntry",
    "MoveCalculationOutput",
    "MoveEntryId",
    "MultiplierRelation",
    "MultiplierVariant",
    "MultiplierVariantId",
    "RuleEligibility",
    "RuleItemMatchResult",
    "RuleItemId",
    "ScenarioCondition",
    "ScenarioConditionId",
    "ScenarioIntegerParameter",
    "ScenarioRuleStack",
    "ScenarioParameterId",
    "ParameterResolution",
    "ScenarioTriggerFact",
    "ScenarioTriggerFactView",
    "EffectMatchContext",
    "EffectMatchResult",
    "EffectMatchStatus",
    "EffectMatcher",
    "EnemyMatchProfile",
    "IdentityResolution",
    "HistoryRecordResolution",
    "DamageEventExecutionTrace",
    "PanelModifierExecutionTrace",
    "EventStatModifier",
    "CalculationRouter",
    "CalculatorExecutionResult",
    "DirectMoveApplicationService",
    "InstantiatedDamageEvent",
    "MatchedEffectApplication",
    "ModifierApplicationResult",
    "MoveCalculationExecution",
    "MoveCalculationRequest",
    "MoveMultiplierResolution",
    "MultiplierResolutionStatus",
    "apply_matched_modifiers",
    "apply_global_panel_effects",
    "calculate_move",
    "instantiate_direct_damage_event",
    "resolve_move_multiplier",
    "element_scope_filter",
]
