// =====================================================================
// AUTOGENERATED CHAR_BUFFS_CONFIG BASED ON SYSTEM PARSING RULES
// =====================================================================

const CHAR_BUFFS_CONFIG = {
  "1011": {
    "self_buffs": [
      {
        "id": "anbi_c2_dmg",
        "name": "影画2：精准放电",
        "desc": "[普通攻击：落雷]命中失衡敌人时，招式造成的伤害提升30%。",
        "active": true,
        "dmg_bonus": 30.0,
        "cinema_req": 2
      },
      {
        "id": "anbi_c6_dmg",
        "name": "影画6：充能电场",
        "desc": "消耗充能使当前招式造成的伤害提升45%。",
        "active": true,
        "dmg_bonus": 45.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1021": {
    "self_buffs": [
      {
        "id": "maomao_core_dmg",
        "name": "核心被动：猫步诡影",
        "desc": "闪避反击命中敌人时，自身造成的伤害提升60%，持续6秒。",
        "active": true,
        "dmg_bonus": 60.0
      },
      {
        "id": "maomao_extra_dmg",
        "name": "额外能力：猫步秀",
        "desc": "强化特殊技时，招式造成的伤害提升35%，最多叠加2层。",
        "active": true,
        "dmg_bonus": 35.0
      },
      {
        "id": "maomao_c4_crit",
        "name": "影画4：磨爪",
        "desc": "发动强化特殊技时，猫又的暴击率提升7%，最多叠加2层(14%)。",
        "active": true,
        "crit_rate": 14.0,
        "cinema_req": 4
      },
      {
        "id": "maomao_c6_crit_dmg",
        "name": "影画6：捕食者血统",
        "desc": "发动连携技或终结技时，猫又的暴击伤害提升18%，最多叠加3层(54%)。",
        "active": true,
        "crit_dmg": 54.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1031": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "nicole_core_def_shred",
        "name": "核心被动：机关箱",
        "desc": "命中敌人时目标防御力降低40%，持续3.8秒 (Rank 7)。",
        "active": true,
        "def_shred": 40.0
      },
      {
        "id": "nicole_c6_crit",
        "name": "影画6：侵蚀能量场",
        "desc": "所有单位对该目标的暴击率提升1.5%，最多叠加10层(15%)。",
        "active": true,
        "crit_rate": 15.0,
        "cinema_req": 6
      }
    ]
  },
  "1041": {
    "self_buffs": [
      {
        "id": "11hao_core_dmg",
        "name": "核心被动：热浪",
        "desc": "触发火力镇压时，招式造成的伤害提升70%。",
        "active": true,
        "dmg_bonus": 70.0
      },
      {
        "id": "11hao_extra_dmg",
        "name": "额外能力：燎原",
        "desc": "火属性伤害提升10%，攻击失衡敌人时额外提升22.5%。",
        "active": true,
        "dmg_bonus": 10.0,
        "tags": [
          "fire",
          "火属性"
        ]
      },
      {
        "id": "11hao_c2_dmg",
        "name": "影画2：高温汇聚",
        "desc": "触发火力镇压时，伤害提升3%，最多叠加12层(36%)。",
        "active": true,
        "dmg_bonus": 36.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1051": {
    "self_buffs": [
      {
        "id": "yidehaili_core_pen",
        "name": "核心被动：拾梦空想 (生命贯穿)",
        "desc": "伊德海莉会额外根据自身最大生命值提高贯穿力，每1点最大生命值将提高0.1点贯穿力；造成冰属性伤害均为贯穿伤害。",
        "active": true
      },
      {
        "id": "yidehaili_extra_low_hp",
        "name": "额外能力：完形叙事",
        "desc": "生命值低于50%时，暴击伤害提升30%。",
        "active": true,
        "crit_dmg": 30.0
      },
      {
        "id": "yidehaili_c2_crit_dmg",
        "name": "影画2：何人于此遐思",
        "desc": "暴击伤害提升40%。",
        "active": true,
        "crit_dmg": 40.0,
        "cinema_req": 2
      },
      {
        "id": "yidehaili_c6_pen_dmg",
        "name": "影画6：终逢安宁之梦",
        "desc": "启谛期间，贯穿伤害提高25%。",
        "active": true,
        "pen_dmg_bonus": 25.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1061": {
    "self_buffs": [
      {
        "id": "kelin_core_dmg",
        "name": "核心被动：专注",
        "desc": "持续斩击时，招式造成的伤害提升37.5%。",
        "active": true,
        "dmg_bonus": 37.5
      },
      {
        "id": "kelin_extra_dmg",
        "name": "额外能力：扫除帮手",
        "desc": "攻击失衡敌人时，自身造成的伤害提升35%。",
        "active": true,
        "dmg_bonus": 35.0
      },
      {
        "id": "kelin_c1_dmg",
        "name": "影画1：开放性创伤",
        "desc": "连携技或终结技命中敌人时，对目标造成的伤害提升12%。",
        "active": true,
        "dmg_bonus": 12.0,
        "cinema_req": 1
      }
    ],
    "team_buffs": []
  },
  "1071": {
    "self_buffs": [
      {
        "id": "caesar_core_atk",
        "name": "核心被动：坚韧之壁 (自身攻击)",
        "desc": "凯撒发动强化特殊技时，自身攻击力提升1000点，持续30秒。",
        "active": true,
        "atk_flat": 1000.0
      },
      {
        "id": "caesar_core_shield",
        "name": "核心被动：坚韧之壁 (护盾)",
        "desc": "凯撒为全队提供等同于初始冲击力14倍+1400点的护盾值。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "shield_flat",
          "based_on": "impact",
          "scale": 14.0,
          "flat": 1400.0
        }
      },
      {
        "id": "caesar_extra_dmg",
        "name": "额外能力：战意激昂",
        "desc": "拥有护盾的角色造成的伤害提升25%，持续10秒。",
        "active": true,
        "dmg_bonus": 25.0
      },
      {
        "id": "caesar_c2_atk",
        "name": "影画2：皇族旗帜",
        "desc": "凯撒影画2：自身攻击力额外提升500点。",
        "active": false,
        "atk_flat": 500.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": [
      {
        "id": "caesar_c1_res_shred",
        "name": "影画1：楔式进军",
        "desc": "荣光之盾存在期间，敌人的全属性伤害抗性降低15%。",
        "active": true,
        "res_shred": 15.0,
        "cinema_req": 1
      }
    ]
  },
  "1081": {
    "self_buffs": [
      {
        "id": "billy_core_dmg",
        "name": "核心被动：稳定据枪",
        "desc": "蹲姿射击后，自身造成的伤害提升50%。",
        "active": true,
        "dmg_bonus": 50.0
      },
      {
        "id": "billy_extra_ult",
        "name": "额外能力：骑士战队",
        "desc": "发动连携技后，下次终结技时，招式造成的伤害提升50%。",
        "active": true,
        "dmg_bonus": 50.0,
        "tags": [
          "ultimate"
        ]
      },
      {
        "id": "billy_c2_dodge",
        "name": "影画2：游斗射术",
        "desc": "闪避反击造成的伤害提升25%。",
        "active": true,
        "dmg_bonus": 25.0,
        "tags": [
          "dodge"
        ],
        "cinema_req": 2
      },
      {
        "id": "billy_c6_stacked",
        "name": "影画6：星徽-英雄时刻",
        "desc": "命中敌人10次时，比利造成的伤害提升6%，最多叠加5层(30%)。",
        "active": true,
        "dmg_bonus": 30.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1091": {
    "self_buffs": [
      {
        "id": "ya_extra_basic_dmg",
        "name": "额外能力：同沐霜雪",
        "desc": "普通攻击：霜月造成的伤害提升60%。",
        "active": true,
        "dmg_bonus": 60.0,
        "tags": [
          "basic"
        ]
      },
      {
        "id": "ya_c1_def_shred",
        "name": "影画1：雪上加霜",
        "desc": "霜月架势期间，每消耗1点落霜无视目标6%防御力，最多叠加6层(36%)。",
        "active": true,
        "def_shred": 36.0,
        "cinema_req": 1
      },
      {
        "id": "ya_c2_crit",
        "name": "影画2：吐纳法",
        "desc": "星见雅的暴击率提升15%。",
        "active": true,
        "crit_rate": 15.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1101": {
    "self_buffs": [
      {
        "id": "kelita_extra_dmg",
        "name": "额外能力：白祇管理学",
        "desc": "连携技对失衡状态敌人造成的伤害提升35%。",
        "active": true,
        "dmg_bonus": 35.0,
        "tags": [
          "chain"
        ]
      },
      {
        "id": "kelita_c4_dmg",
        "name": "影画4：熔炉余温",
        "desc": "连携技或终结技命中失衡敌人时，招式造成的伤害提升18%。",
        "active": true,
        "dmg_bonus": 18.0,
        "cinema_req": 4
      }
    ],
    "team_buffs": []
  },
  "1111": {
    "self_buffs": [
      {
        "id": "antong_core_dmg",
        "name": "核心被动：兄弟齐心！",
        "desc": "发动电钻攻击时，招式造成的伤害提升40%。",
        "active": true,
        "dmg_bonus": 40.0
      },
      {
        "id": "antong_c6_dmg",
        "name": "影画6：突破极限",
        "desc": "爆发状态普攻和闪避反击造成的伤害提升4%，最多叠加6层(24%)。",
        "active": true,
        "dmg_bonus": 24.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": [
      {
        "id": "antong_c4_team_crit",
        "name": "影画4：一起燃烧！",
        "desc": "全队角色暴击率提升10%，持续12秒。",
        "active": true,
        "crit_rate": 10.0,
        "cinema_req": 4
      }
    ]
  },
  "1121": {
    "self_buffs": [
      {
        "id": "ben_extra_crit",
        "name": "额外能力：协议合同",
        "desc": "拥有护盾时，角色的暴击率提升16%。",
        "active": true,
        "crit_rate": 16.0
      },
      {
        "id": "ben_c4_dmg",
        "name": "影画4：灵活应变",
        "desc": "成功格挡攻击时，后继反击造成的伤害提升30%。",
        "active": true,
        "dmg_bonus": 30.0,
        "cinema_req": 4
      }
    ],
    "team_buffs": [
      {
        "id": "ben_core_shield",
        "name": "核心被动：守卫",
        "desc": "本的核心被动提供护盾，基于其初始攻击力的80%，最多3000点。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "shield_flat",
          "based_on": "atk",
          "scale": 0.8,
          "cap": 3000.0
        }
      }
    ]
  },
  "1131": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "soukaku_core_atk",
        "name": "核心被动：风气",
        "desc": "霜染刃旗状态使全队角色攻击力提升，等同于苍角40%初始攻击力，最多提升1000点 (Rank 7)。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "atk",
          "scale": 0.4,
          "cap": 1000.0
        }
      },
      {
        "id": "soukaku_extra_ice_dmg",
        "name": "额外能力：团膳套餐",
        "desc": "全队角色造成的冰属性伤害提升20%，持续22秒。",
        "active": true,
        "dmg_bonus": 20.0,
        "tags": [
          "ice",
          "冰属性"
        ]
      },
      {
        "id": "soukaku_c4_res_shred",
        "name": "影画4：失温症",
        "desc": "目标的冰属性伤害抗性降低10%，持续8秒。",
        "active": true,
        "res_shred": 10.0,
        "tags": [
          "ice",
          "冰属性"
        ],
        "cinema_req": 4
      },
      {
        "id": "soukaku_c6_dmg",
        "name": "影画6：朔风侵袭",
        "desc": "霜染刃旗状态下，强化普攻和强化冲刺攻击造成的伤害提升45%。",
        "active": true,
        "dmg_bonus": 45.0,
        "cinema_req": 6
      }
    ]
  },
  "1141": {
    "self_buffs": [
      {
        "id": "laikuen_core_dmg",
        "name": "核心被动：金属狼足",
        "desc": "莱卡恩完成蓄力或发动闪避反击时，招式造成的伤害提升30%，攻击失衡敌人时无视25%伤害抗性。",
        "active": true,
        "dmg_bonus": 30.0,
        "res_shred": 25.0
      },
      {
        "id": "laikuen_c6_dmg",
        "name": "影画6：冷酷猎手",
        "desc": "蓄力攻击命中敌人时，对目标造成的伤害提升10%，最多叠加5层(50%)。",
        "active": true,
        "dmg_bonus": 50.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1151": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "lucy_active_atk",
        "name": "特殊技：加油！状态",
        "desc": "友方单位攻击力提升，等同于露西22.6%初始攻击力+88点，最高不超过600点 (Lv 12)。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "atk",
          "scale": 0.226,
          "flat": 88.0,
          "cap": 600.0
        }
      },
      {
        "id": "lucy_c4_crit_dmg",
        "name": "影画4：无规则球赛",
        "desc": "友方单位，暴击伤害额外提升10%。",
        "active": true,
        "crit_dmg": 10.0,
        "cinema_req": 4
      }
    ]
  },
  "1161": {
    "self_buffs": [
      {
        "id": "laite_core_res_shred",
        "name": "核心被动：助燃剂",
        "desc": "士气喷发状态下使敌人受到的冰属性和火属性伤害抗性各降低15%。",
        "active": true,
        "res_shred": 15.0,
        "tags": [
          "fire",
          "ice",
          "火属性",
          "冰属性"
        ]
      }
    ],
    "team_buffs": [
      {
        "id": "laite_extra_dmg_bonus",
        "name": "额外能力：斗志昂扬",
        "desc": "士气喷发状态下，全队角色获得昂扬，最多20层；每层使角色造成的伤害提升1.25%，最高75%。",
        "active": true,
        "dmg_bonus": 25.0
      },
      {
        "id": "laite_c1_dmg",
        "name": "影画1：常胜冠军",
        "desc": "冰属性和火属性伤害抗性额外降低30%。",
        "active": true,
        "res_shred": 30.0,
        "tags": [
          "fire",
          "ice"
        ],
        "cinema_req": 1
      }
    ]
  },
  "1171": {
    "self_buffs": [
      {
        "id": "bonnie_extra_fire_anomaly",
        "name": "额外能力：加量不加价",
        "desc": "触发余烬效果时，目标每拥有一层热意洞穿，本次攻击的穿透率提升4%，最多提升20%。",
        "active": true,
        "pen_rate": 20.0
      },
      {
        "id": "bonnie_c4_crit",
        "name": "影画4：超绝燃油补给",
        "desc": "强化特殊技命中敌人时，招式的暴击率提升30%。",
        "active": true,
        "crit_rate": 30.0,
        "tags": [
          "special"
        ],
        "cinema_req": 4
      },
      {
        "id": "bonnie_c6_res_ignore",
        "name": "影画6：盛焰邀约",
        "desc": "强化特殊技：灼热摇荡法·双份命中后，强化特殊技、余烬、灼烧伤害将无视目标25%火属性伤害抗性。",
        "active": true,
        "res_ignore": 25.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1181": {
    "self_buffs": [
      {
        "id": "gelisi_extra_anomaly_dmg",
        "name": "额外能力：技术支持班组",
        "desc": "格莉丝强化特殊技命中敌人时，目标下次被施加感电效果时，受到的感电伤害提升18%，最多叠加2层(36%)。",
        "active": true,
        "dmg_bonus": 36.0,
        "tags": [
          "special"
        ]
      },
      {
        "id": "gelisi_c2_res_shred",
        "name": "影画2：电致击穿",
        "desc": "投掷手雷命中敌人时，目标的电属性伤害抗性降低8.5%，持续8秒。",
        "active": true,
        "res_shred": 8.5,
        "tags": [
          "electric",
          "电属性"
        ],
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1191": {
    "self_buffs": [
      {
        "id": "ailian_core_crit_dmg",
        "name": "核心被动：凌牙厉齿",
        "desc": "艾莲在冲刺攻击中发动蓄力剪击，招式的暴击伤害提升100%。",
        "active": true,
        "crit_dmg": 100.0
      },
      {
        "id": "ailian_extra_ice_dmg",
        "name": "额外能力：风暴潮",
        "desc": "艾莲造成冰属性伤害时，后继冰属性伤害提升3%，最多叠加10层(30%)。",
        "active": true,
        "dmg_bonus": 30.0,
        "tags": [
          "ice",
          "冰属性"
        ]
      },
      {
        "id": "ailian_c1_crit",
        "name": "影画1：凛冬前兆",
        "desc": "每消耗1点急冻充能，艾莲的暴击率提升2%，最多叠加6层(12%)。",
        "active": true,
        "crit_rate": 12.0,
        "cinema_req": 1
      },
      {
        "id": "ailian_c2_crit_dmg",
        "name": "影画2：冰洋掠食者",
        "desc": "发动强化特殊技时，每拥有1点急冻充能，暴击伤害提升20%，最多提升60%。",
        "active": true,
        "crit_dmg": 60.0,
        "tags": [
          "special"
        ],
        "cinema_req": 2
      },
      {
        "id": "ailian_c6_pen",
        "name": "影画6：盛宴时分",
        "desc": "发动强化特殊技、连携技或获得快蓄时，艾莲的穿透率提升20%，持续6秒。",
        "active": true,
        "pen_rate": 20.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1201": {
    "self_buffs": [
      {
        "id": "youzhen_core_crit",
        "name": "核心被动：破晓",
        "desc": "飞弦斩、逐雷和终结技的暴击率提升25%，每层锋芒使相关招式暴击伤害提升12%，最多叠加6层(72%)。",
        "active": true,
        "crit_rate": 25.0,
        "crit_dmg": 72.0
      },
      {
        "id": "youzhen_extra_dmg",
        "name": "额外能力：超频",
        "desc": "悠真攻击命中处于失衡状态或属性异常状态下的敌人时，自身造成的伤害提升40%。",
        "active": true,
        "dmg_bonus": 40.0
      },
      {
        "id": "youzhen_c2_dmg",
        "name": "影画2：挥霍",
        "desc": "拥有电掣时，飞弦斩造成的伤害提升50%。",
        "active": true,
        "dmg_bonus": 50.0,
        "tags": [
          "dodge"
        ],
        "cinema_req": 2
      },
      {
        "id": "youzhen_c6_res_ignore",
        "name": "影画6：会心",
        "desc": "悠真将无视其15%电属性伤害抗性，持续12秒。",
        "active": true,
        "res_ignore": 15.0,
        "tags": [
          "electric",
          "电属性"
        ],
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1211": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "lina_core_pen",
        "name": "核心被动：迷你毁灭拍档",
        "desc": "其他角色的穿透率随丽娜自身的穿透率提升，提升效果等同于丽娜25%穿透率+12%，最高提升30%。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "pen_rate",
          "based_on": "pen_rate",
          "scale": 0.25,
          "flat": 12.0,
          "cap": 30.0
        }
      },
      {
        "id": "lina_extra_electric_dmg",
        "name": "额外能力：完美舞会",
        "desc": "场上存在感电状态下的敌人时，全队角色造成的电属性伤害提升10%。",
        "active": true,
        "dmg_bonus": 10.0,
        "tags": [
          "electric",
          "电属性"
        ]
      },
      {
        "id": "lina_c6_electric_dmg",
        "name": "影画6：雷雨夜惊魂",
        "desc": "全队角色造成的电属性伤害提升15%，持续8秒。",
        "active": true,
        "dmg_bonus": 15.0,
        "tags": [
          "electric",
          "电属性"
        ],
        "cinema_req": 6
      }
    ]
  },
  "1221": {
    "self_buffs": [
      {
        "id": "liu_core_dmg",
        "name": "核心被动：月蚀",
        "desc": "月城柳发动强化特殊技后，自身造成的伤害提升20%。",
        "active": true,
        "dmg_bonus": 20.0
      },
      {
        "id": "liu_c6_dmg",
        "name": "影画6：非人之血",
        "desc": "森罗万象状态持续期间，强化特殊技造成的伤害提升20%。",
        "active": true,
        "dmg_bonus": 20.0,
        "tags": [
          "special"
        ],
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1241": {
    "self_buffs": [
      {
        "id": "zhuyan_core_dmg",
        "name": "核心被动：特种弹药",
        "desc": "压制模式下消耗强化霰弹进行攻击时，招式造成的伤害提升40%，攻击失衡状态敌人时额外提升40%。",
        "active": true,
        "dmg_bonus": 40.0
      },
      {
        "id": "zhuyan_extra_crit",
        "name": "额外能力：武装协同",
        "desc": "朱鸢发动强化特殊技、连携技或终结技时，自身暴击率提升30%。",
        "active": true,
        "crit_rate": 30.0,
        "tags": [
          "special",
          "chain",
          "ultimate"
        ]
      }
    ],
    "team_buffs": []
  },
  "1251": {
    "self_buffs": [
      {
        "id": "qingyi_extra_atk",
        "name": "额外能力：阳关三叠",
        "desc": "冲击力高于120点时，每超过1点冲击力使自身的攻击力提升6点，最多提升600点。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "impact",
          "offset": 120.0,
          "scale": 6.0,
          "cap": 600.0
        }
      },
      {
        "id": "qingyi_c1_crit_def",
        "name": "影画1：介电击穿",
        "desc": "醉花月云转命中敌人时，敌人防御力降低15%，暴击率提升20%。",
        "active": true,
        "crit_rate": 20.0,
        "def_shred": 15.0,
        "cinema_req": 1
      },
      {
        "id": "qingyi_c6_crit_dmg_res",
        "name": "影画6：奇经八脉",
        "desc": "醉花月云转的暴击伤害额外提升100%；目标的全属性伤害抗性降低20%。",
        "active": true,
        "crit_dmg": 100.0,
        "res_shred": 20.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1261": {
    "self_buffs": [
      {
        "id": "jian_c4_anomaly_dmg",
        "name": "影画4：因势利导",
        "desc": "全队角色造成的属性异常伤害提升18%，持续15秒。",
        "active": true,
        "dmg_bonus": 18.0,
        "cinema_req": 4
      },
      {
        "id": "jian_c6_crit_state",
        "name": "影画6：肮脏技巧",
        "desc": "狂热状态下，简的暴击率提升20%，暴击伤害提升40%。",
        "active": true,
        "crit_rate": 20.0,
        "crit_dmg": 40.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1271": {
    "self_buffs": [
      {
        "id": "seth_c6_crit_dmg",
        "name": "影画6：理想主义",
        "desc": "赛斯在终结一击命中敌人时，本次攻击必定触发暴击，且暴击伤害提升60%。",
        "active": true,
        "crit_dmg": 60.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": [
      {
        "id": "seth_core_shield",
        "name": "核心被动：电磁护盾",
        "desc": "赛斯核心被动提供护盾，基于初始攻击力的80%，最多3000点。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "shield_flat",
          "based_on": "atk",
          "scale": 0.8,
          "cap": 3000.0
        }
      },
      {
        "id": "seth_core_anomaly",
        "name": "核心被动：感电场",
        "desc": "赛斯的核心被动为全队角色提升异常精通100点。",
        "active": true,
        "anomaly_proficiency": 100.0
      },
      {
        "id": "seth_extra_res_shred",
        "name": "额外能力：意气风发",
        "desc": "赛斯发动连携技命中敌人时，目标的全属性异常积蓄抗性降低20%，持续20秒。",
        "active": true,
        "res_shred": 20.0
      }
    ]
  },
  "1281": {
    "self_buffs": [
      {
        "id": "paipai_extra_dmg",
        "name": "额外能力：同步疾驰",
        "desc": "派派拥有20层或以上动力时，全队角色造成的伤害提升18%。",
        "active": true,
        "dmg_bonus": 18.0
      },
      {
        "id": "paipai_c2_dmg",
        "name": "影画2：上进心",
        "desc": "在特殊技中发动冲撞命中敌人时，招式造成的伤害提升10%。",
        "active": true,
        "dmg_bonus": 10.0,
        "tags": [
          "special"
        ],
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1291": {
    "self_buffs": [
      {
        "id": "hugo_core_state",
        "name": "核心被动：终末裁决 (暗渊回响)",
        "desc": "[暗渊回响]状态下雨果的暴击率提升12%，暴击伤害提升25%。",
        "active": true,
        "crit_rate": 12.0,
        "crit_dmg": 25.0
      },
      {
        "id": "hugo_core_atk_link",
        "name": "核心被动：终末裁决 (击破联动)",
        "desc": "队伍中存在其他1/2名击破角色时，雨果的攻击力提升300/900点。",
        "active": true,
        "dynamic_team_check": {
          "check_specialty": "击破",
          "values": {
            "1": 300.0,
            "2": 900.0
          },
          "stat_to_add": "atk_flat"
        }
      },
      {
        "id": "hugo_core_execute",
        "name": "核心被动：终末裁决 (决算)",
        "desc": "强化特殊技或终结技触发[决算]时，终结一击倍率提升1000%至4400%。",
        "active": false,
        "dmg_multiplier": 4400.0,
        "tags": [
          "special",
          "ultimate"
        ]
      },
      {
        "id": "hugo_extra_dmg",
        "name": "额外能力：终焉序曲",
        "desc": "连携技伤害提升15%；触发决算时伤害提升40%。",
        "active": true,
        "dmg_bonus": 40.0,
        "tags": [
          "special",
          "ultimate",
          "chain"
        ]
      },
      {
        "id": "hugo_c1_exec_crit",
        "name": "影画1：仇恨之子",
        "desc": "[暗渊回响]下触发决算时，招式暴击率提升12%，暴击伤害提升30%。",
        "active": true,
        "crit_rate": 12.0,
        "crit_dmg": 30.0,
        "tags": [
          "special",
          "ultimate"
        ],
        "cinema_req": 1
      },
      {
        "id": "hugo_c2_def_ignore",
        "name": "影画2：内在小孩",
        "desc": "触发决算时，招式无视目标15%防御力。",
        "active": true,
        "def_ignore": 15.0,
        "tags": [
          "special",
          "ultimate"
        ],
        "cinema_req": 2
      },
      {
        "id": "hugo_c4_res_ignore",
        "name": "影画4：拟剧论",
        "desc": "攻击命中无视目标12%冰抗。",
        "active": true,
        "res_ignore": 12.0,
        "tags": [
          "ice",
          "冰属性"
        ],
        "cinema_req": 4
      }
    ],
    "team_buffs": []
  },
  "1301": {
    "self_buffs": [
      {
        "id": "ofis_core_crit_dmg",
        "name": "核心被动：衔风驭火",
        "desc": "奥菲丝的暴击率提升25%，追加攻击造成的伤害提升85%。",
        "active": true,
        "crit_rate": 25.0,
        "dmg_bonus": 85.0,
        "atk_flat": 280.0
      },
      {
        "id": "ofis_c1_res_dmg",
        "name": "影画1：豪华猫屋",
        "desc": "发动特殊技/强化特殊技等造成的伤害无视15%火属性伤害抗性；拥有准星聚焦的代理人攻击造成的伤害提升20%。",
        "active": true,
        "res_ignore": 15.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 1
      },
      {
        "id": "ofis_c2_crit_dmg",
        "name": "影画2：天赋人权",
        "desc": "奥菲丝的暴击伤害提升40%，暴击率提升15%。",
        "active": true,
        "crit_rate": 15.0,
        "crit_dmg": 40.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1311": {
    "self_buffs": [
      {
        "id": "yaojiayin_special_crit_dmg",
        "name": "特殊技：咏叹华彩状态 (自身爆伤)",
        "desc": "耀嘉音进入咏叹华彩状态后，全队角色暴击伤害提升25%。",
        "active": true,
        "crit_dmg": 25.0
      },
      {
        "id": "yaojiayin_c6_resonance",
        "name": "影画6：我们即是世界",
        "desc": "在咏叹华彩状态下释放的震音和音簇的伤害倍率提升至原本的200%，暴击率提升80%。",
        "active": false,
        "crit_rate": 80.0,
        "dmg_multiplier": 100.0,
        "tags": [
          "resonance_attack"
        ],
        "cinema_req": 6
      }
    ],
    "team_buffs": [
      {
        "id": "yaojiayin_special_team_dmg",
        "name": "特殊技：咏叹华彩状态 (全队增伤+爆伤)",
        "desc": "耀嘉音进入咏叹华彩状态后，全队角色造成的伤害提升20%，全队角色暴击伤害提升25%。",
        "active": true,
        "dmg_bonus": 20.0,
        "crit_dmg": 25.0
      },
      {
        "id": "yaojiayin_core_atk",
        "name": "核心被动：如歌的行板",
        "desc": "在咏叹华彩状态下，耀嘉音和入场角色的攻击力提升，提升效果等同于耀嘉音初始攻击力的35%，最高不超过1200点 (Rank 7)。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "atk",
          "scale": 0.35,
          "cap": 1200.0
        }
      },
      {
        "id": "yaojiayin_c1_res_shred",
        "name": "影画1：十二平均律",
        "desc": "目标的全属性伤害抗性降低6%，最多叠加3层 (18%)。",
        "active": true,
        "res_shred": 18.0,
        "cinema_req": 1
      },
      {
        "id": "yaojiayin_c2_core_boost",
        "name": "影画2：贪心艺术",
        "desc": "[核心被动]中的攻击力提升效果额外提升19%，上限额外提升400点。",
        "active": true,
        "dynamic_modifier": {
          "target_buff_id": "yaojiayin_core_atk",
          "scale_add": 0.19,
          "cap_add": 400.0
        },
        "cinema_req": 2
      }
    ]
  },
  "1321": {
    "self_buffs": [
      {
        "id": "evelyn_core_crit",
        "name": "核心被动：缠丝",
        "desc": "进入牵缠禁制时，伊芙琳的暴击率提升25%，退出状态后保有10秒。",
        "active": true,
        "crit_rate": 25.0
      },
      {
        "id": "evelyn_extra_dmg",
        "name": "额外能力：潜袭支点",
        "desc": "连携技和终结技伤害提升30%；若暴击率大于等于80%时，这些招式伤害倍率提升至125%。",
        "active": true,
        "dmg_bonus": 30.0,
        "tags": [
          "chain",
          "ultimate"
        ]
      },
      {
        "id": "evelyn_c1_def_ignore",
        "name": "影画1：织梦",
        "desc": "攻击带有禁锢效果的敌人时，伊芙琳无视目标12%防御力。",
        "active": true,
        "def_ignore": 12.0,
        "cinema_req": 1
      },
      {
        "id": "evelyn_c2_atk_bonus",
        "name": "影画2：赴火之舞",
        "desc": "伊芙琳的攻击力提升15%。",
        "active": true,
        "atk_pct": 15.0,
        "cinema_req": 2
      },
      {
        "id": "evelyn_c4_crit_dmg",
        "name": "影画4：命运的弦音",
        "desc": "获得护盾时，暴击伤害提升40%。",
        "active": true,
        "crit_dmg": 40.0,
        "cinema_req": 4
      }
    ],
    "team_buffs": []
  },
  "1331": {
    "self_buffs": [
      {
        "id": "weiweiyan_extra_anomaly",
        "name": "额外能力：以太共鸣",
        "desc": "薇薇安在特定状态下提升以太属性异常伤害。",
        "active": true,
        "dmg_bonus": 20.0,
        "tags": [
          "ether",
          "以太"
        ]
      }
    ],
    "team_buffs": []
  },
  "1341": {
    "self_buffs": [
      {
        "id": "zhao_self_crit",
        "name": "核心被动：最佳同事",
        "desc": "照会额外根据初始最大生命值提高暴击率，每1000点初始最大生命值提高1.4%暴击率。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "crit_rate",
          "based_on": "hp",
          "scale": 0.0014
        }
      }
    ],
    "team_buffs": [
      {
        "id": "zhao_team_shield_atk",
        "name": "核心被动：以太帷幕·涌泉",
        "desc": "全队角色最大生命值提升5%；开启以太帷幕时，全队角色攻击力提升1000点。",
        "active": true,
        "atk_flat": 1000.0,
        "hp_pct": 5.0
      },
      {
        "id": "zhao_extra_dmg",
        "name": "额外能力：凝聚力",
        "desc": "照的初始最大生命值高于15000点时，每超过400点初始最大生命值，可使增伤效果额外提升1%，最高总共提升至40% (Rank 7)。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "dmg_bonus",
          "based_on": "hp",
          "offset": 15000.0,
          "scale": 0.0025,
          "flat": 10.0,
          "cap": 40.0
        }
      },
      {
        "id": "zhao_c1_res_shred",
        "name": "影画1：凛然裁决",
        "desc": "切换为非操作角色时，使全队角色造成的伤害无视目标15%全属性伤害抗性。",
        "active": true,
        "res_shred": 15.0,
        "cinema_req": 1
      },
      {
        "id": "zhao_c2_team_atk",
        "name": "影画2：黑枝前辈",
        "desc": "使全队其他角色提升15%攻击力。",
        "active": true,
        "atk_pct": 15.0,
        "cinema_req": 2
      }
    ]
  },
  "1351": {
    "self_buffs": [
      {
        "id": "pokona_core_dmg",
        "name": "核心被动",
        "desc": "波可娜发动强化特殊技或连携技造成的伤害提升。",
        "active": true,
        "dmg_bonus": 30.0,
        "tags": [
          "special",
          "chain"
        ]
      }
    ],
    "team_buffs": []
  },
  "1361": {
    "self_buffs": [
      {
        "id": "banji_extra_daze",
        "name": "额外能力：灵目银灯",
        "desc": "队伍中存在[强攻]角色或与自身属性相同的角色时触发：「扳机」的暴击率高于40%时，每超过1%暴击率会使自身发动[追加攻击]造成的失衡值提升1.5%，最多提升75%。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "daze_bonus",
          "based_on": "crit_rate",
          "offset": 40.0,
          "scale": 1.5,
          "cap": 75.0
        },
        "tags": [
          "追加攻击",
          "follow_up"
        ]
      }
    ],
    "team_buffs": [
      {
        "id": "banjitrigger_core_vuln",
        "name": "核心被动：破隙幽瞳",
        "desc": "「扳机」发动[追加攻击]命中敌人时，目标的失衡易伤倍率提升35%，持续5秒，通过这种途径施加的失衡易伤倍率提升效果，在目标未进入失衡状态时亦可生效。",
        "active": true
      },
      {
        "id": "banjitrigger_c1_vuln",
        "name": "影画1：精准感知",
        "desc": "通过[核心被动：破隙幽瞳]施加的失衡易伤倍率额外提升20%",
        "active": true,
        "cinema_req": 1
      }
    ]
  },
  "1371": {
    "self_buffs": [
      {
        "id": "yixuan_core_dmg",
        "name": "核心被动：术法宗师 (招式增伤)",
        "desc": "仪玄施展普通攻击、强化特殊技、连携技、终结技造成的伤害提升60%。",
        "active": true,
        "dmg_bonus": 60.0
      },
      {
        "id": "yixuan_extra_ning_shen",
        "name": "额外能力：玄墨暗涌 (凝神状态)",
        "desc": "发动终结技后，仪玄进入[凝神]状态，自身暴击伤害提升40%，持续15秒。",
        "active": true,
        "crit_dmg": 40.0
      },
      {
        "id": "yixuan_extra_stun_dmg",
        "name": "额外能力：玄墨暗涌 (失衡伤害提升)",
        "desc": "强化特殊技命中处于失衡状态下的敌人时，伤害提升30%。",
        "active": true,
        "dmg_bonus": 30.0
      },
      {
        "id": "yixuan_c1_crit_rate",
        "name": "影画1：清灵道心",
        "desc": "进入战场时，暴击率提升10%。",
        "active": true,
        "crit_rate": 10.0,
        "cinema_req": 1
      },
      {
        "id": "yixuan_c2_res_shred",
        "name": "影画2：消灾渡厄",
        "desc": "终结技或强化特殊技造成伤害时，无视目标15%以太伤害抗性。",
        "active": true,
        "res_shred": 15.0,
        "cinema_req": 2
      },
      {
        "id": "yixuan_c4_special_dmg",
        "name": "影画4：术道归一",
        "desc": "每有一层[静心]效果，下一次强化特殊技造成的伤害提升30%（最多叠加2层即60%）。",
        "active": true,
        "dmg_bonus": 60.0,
        "cinema_req": 4
      },
      {
        "id": "yixuan_c6_pen_dmg",
        "name": "影画6：永不结束的旅途",
        "desc": "[凝神]状态下，仪玄的贯穿伤害提高20%。",
        "active": true,
        "pen_dmg_bonus": 20.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1381": {
    "self_buffs": [
      {
        "id": "zeroanbi_core_crit",
        "name": "核心被动：电磁强攻",
        "desc": "零号·安比的核心被动提升自身暴击率和电属性伤害。",
        "active": true,
        "crit_rate": 20.0,
        "dmg_bonus": 30.0,
        "tags": [
          "electric",
          "电属性"
        ]
      }
    ],
    "team_buffs": []
  },
  "1391": {
    "self_buffs": [
      {
        "id": "jufu_core_fire_dmg",
        "name": "核心被动：橘子轰炸",
        "desc": "橘福福核心被动提供火属性伤害加成和失衡期增伤。",
        "active": true,
        "dmg_bonus": 35.0,
        "tags": [
          "fire",
          "火属性"
        ]
      }
    ],
    "team_buffs": []
  },
  "1401": {
    "self_buffs": [
      {
        "id": "alice_extra_anomaly_proficiency",
        "name": "额外能力：寻奇猎幽",
        "desc": "队伍中存在另一名[异常]或[支援]角色时触发：若爱丽丝的异常掌控大于140点，每超过1点异常掌控会提升1.6点异常精通。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "anomaly_proficiency",
          "based_on": "anomaly_mastery_realtime",
          "offset": 140.0,
          "scale": 1.6
        }
      },
      {
        "id": "alice_core_disorder_bonus",
        "name": "核心被动：剑心双虹 (紊乱倍率)",
        "desc": "物理异常状态下的敌人被触发[紊乱]时，每有1秒物理异常状态剩余时间，紊乱效果的伤害倍率提升18%，最多提升180%。",
        "active": true,
        "disorder_ratio_bonus": 180.0
      },
      {
        "id": "alice_c4_res_ignore",
        "name": "影画 4：唇间的迷迭香",
        "desc": "爱丽丝无视目标10%物理伤害抗性。",
        "active": true,
        "res_ignore": 10.0,
        "tags": [
          "physical",
          "物理"
        ],
        "cinema_req": 4
      }
    ],
    "team_buffs": [
      {
        "id": "alice_c1_def_shred",
        "name": "影画 1：掌心的芫荽",
        "desc": "爱丽丝触发[极性强击]时，回复25点[剑仪]；爱丽丝触发[强击]时，目标的防御力降低20%，持续30秒。",
        "active": true,
        "def_shred": 20.0,
        "cinema_req": 1
      },
      {
        "id": "alice_c2_team_dmg",
        "name": "影画 2：剑尖的鼠尾草",
        "desc": "全队角色造成的[强击]伤害提升15%；物理异常状态下的敌人被结算的[紊乱]伤害提升15%。",
        "active": true,
        "dmg_bonus": 15.0,
        "tags": [
          "anomaly",
          "physical",
          "物理"
        ],
        "cinema_req": 2
      }
    ]
  },
  "1411": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "yuzuha_team_atk",
        "name": "核心被动：奇巧缤纷",
        "desc": "狸之愿会提供等同于柚叶40%初始攻击力的攻击力加成，最多提升1200点，并使伤害提升15% (Rank 7)。",
        "active": true,
        "dmg_bonus": 15.0,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "atk",
          "scale": 0.4,
          "cap": 1200.0
        }
      },
      {
        "id": "yuzuha_extra_anomaly",
        "name": "额外能力：人多乐趣大",
        "desc": "若柚叶的异常掌控大于100点，每超过1点异常掌控会使角色的属性异常积蓄效率、异常伤害和紊乱伤害提升0.2%，最高20%。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "anomaly_buffs",
          "based_on": "anomaly_mastery_realtime",
          "offset": 100.0,
          "scale": 0.002,
          "cap": 0.2
        }
      },
      {
        "id": "yuzuha_c1_res_shred",
        "name": "影画1：幸运体质",
        "desc": "甜蜜惊吓状态下的敌人全属性伤害抗性降低10%；额外能力中属性异常伤害和紊乱伤害增益效果提升至原本的130%。",
        "active": true,
        "res_shred": 10.0,
        "dynamic_modifier": {
          "target_buff_id": "yuzuha_extra_anomaly",
          "scale_multiplier": 1.3
        },
        "cinema_req": 1
      },
      {
        "id": "yuzuha_c2_dmg_accum",
        "name": "影画2：趣友云集",
        "desc": "强化特殊技或终结技命中时，全队伤害提升15%，属性异常积蓄效率提升15%。",
        "active": true,
        "dmg_bonus": 15.0,
        "anomaly_accumulation_rate": 15.0,
        "cinema_req": 2
      },
      {
        "id": "yuzuha_c6_disorder",
        "name": "影画6：落地生根",
        "desc": "强力炮弹命中时，使全队角色紊乱效果的伤害倍率提升105%，最多叠加3层 (315%)。",
        "active": true,
        "disorder_dmg_multiplier": 315.0,
        "cinema_req": 6
      }
    ]
  },
  "1421": {
    "self_buffs": [
      {
        "id": "panyinhu_core_dmg",
        "name": "核心被动：壶中乾坤",
        "desc": "潘引壶拥有护盾时，自身造成的伤害提升。",
        "active": true,
        "dmg_bonus": 20.0
      }
    ],
    "team_buffs": [
      {
        "id": "panyinhu_team_shield",
        "name": "核心被动：护盾联动",
        "desc": "潘引壶核心被动为全队提供护盾，基于自身初始防御力转换。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "shield_flat",
          "based_on": "def",
          "scale": 1.5,
          "cap": 5000.0
        }
      },
      {
        "id": "panyinhu_tongqiao",
        "name": "核心被动：通窍状态 (队友贯穿)",
        "desc": "潘引壶发动[强化特殊技]后，入场的下一位代理人获得[通窍]效果，提供潘引壶初始攻击力18%的贯穿力提升，最多不超过540点。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "pen_flat",
          "based_on": "atk",
          "scale": 0.18,
          "cap": 540.0
        }
      }
    ]
  },
  "1431": {
    "self_buffs": [
      {
        "id": "shungu_core_state",
        "name": "核心被动：明心境/合道",
        "desc": "明心状态下，暴击率提升30%，伤害提升25% (Rank 7)。",
        "active": true,
        "crit_rate": 30.0,
        "dmg_bonus": 25.0
      },
      {
        "id": "shungu_c1_def_ignore",
        "name": "影画1：梦中身",
        "desc": "进入战场时，获得6点[青溟剑势]，在勘域模式中此效果180秒内最多触发一次；[核心被动：照破无明]中[合道]效果额外使造成的伤害提升10%，无视目标20%防御力。",
        "active": true,
        "dmg_bonus": 10.0,
        "def_ignore": 20.0,
        "cinema_req": 1
      },
      {
        "id": "shungu_c2_def_ignore",
        "name": "影画2：光与影",
        "desc": "[强化特殊技：明心境·飞光]和[终结技：斩妄开天]造成的伤害无视目标40%防御力。",
        "active": true,
        "def_ignore": 40.0,
        "tags": ["special", "chain"],
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1441": {
    "self_buffs": [
      {
        "id": "masato_self_pen",
        "name": "核心被动：熔锋之势 (生命贯穿)",
        "desc": "额外根据自身最大生命值提高贯穿力，每1点最大生命值将提高0.1点贯穿力。",
        "active": true
      },
      {
        "id": "masato_state_buff",
        "name": "核心被动：熔锋状态",
        "desc": "[熔锋] 状态下，暴击率提升10%，火属性伤害提升20%。",
        "active": false,
        "crit_rate": 10.0,
        "dmg_bonus": 20.0,
        "tags": [
          "fire",
          "火属性"
        ]
      },
      {
        "id": "masato_crit_dmg_boost",
        "name": "核心被动：斩击耗血",
        "desc": "斩击消耗生命值时，使此次攻击的暴击伤害提升50%。",
        "active": true,
        "crit_dmg": 50.0
      },
      {
        "id": "masato_c1_dmg_lost",
        "name": "影画1：流浪生存法则",
        "desc": "每有1%已损失生命值使攻击造成的火属性伤害提升0.4%，最高提升20%。",
        "active": true,
        "dmg_bonus": 20.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 1
      },
      {
        "id": "masato_c2_res_shred",
        "name": "影画2：昼夜、厨房与爱",
        "desc": "[熔锋] 状态下，无视目标8%火属性抗性。",
        "active": true,
        "res_ignore": 8.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1451": {
    "self_buffs": [],
    "team_buffs": [
      {
        "id": "luxia_core_hp",
        "name": "核心被动：迷途夜颂 (以太帷幕·涌泉)",
        "desc": "以太帷幕·涌泉生效期间，全队角色最大生命值提升5%。",
        "active": true,
        "hp_pct": 5.0
      },
      {
        "id": "luxia_core_dmg",
        "name": "核心被动：迷途夜颂 (巡梦童谣)",
        "desc": "处于巡梦童谣状态下时，全队角色造成的伤害提升20%。",
        "active": true,
        "dmg_bonus": 20.0
      },
      {
        "id": "luxia_extra_crit_dmg",
        "name": "额外能力：长夜诗篇",
        "desc": "全队施加[破暗]状态时，额外附加暴击伤害提升30%效果。",
        "active": true,
        "crit_dmg": 30.0
      },
      {
        "id": "luxia_poan",
        "name": "强化特殊技：破暗状态 (全队贯穿)",
        "desc": "为全队提升12点基础贯穿力，并且基于卢西娅的初始最大生命值，每200点生命值额外提升7.4点贯穿力（最多不超过900点）。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "pen_flat",
          "based_on": "hp",
          "scale": 0.037,
          "flat": 12.0,
          "cap": 900.0
        }
      }
    ]
  },
  "1461": {
    "self_buffs": [
      {
        "id": "xide_core_crit",
        "name": "核心被动：电流穿刺",
        "desc": "席德的核心被动提升自身暴击率和暴击伤害。",
        "active": true,
        "crit_rate": 20.0,
        "crit_dmg": 40.0
      },
      {
        "id": "xide_extra_dmg",
        "name": "额外能力：高压电弧",
        "desc": "席德额外能力在特定状态下提升电属性伤害。",
        "active": true,
        "dmg_bonus": 30.0,
        "tags": [
          "electric",
          "电属性"
        ]
      }
    ],
    "team_buffs": []
  },
  "1471": {
    "self_buffs": [
      {
        "id": "banyue_core_pen",
        "name": "核心被动：群山如我 (生命贯穿)",
        "desc": "般岳会额外根据自身最大生命值提高贯穿力，每1点最大生命值将提高0.1点贯穿力；火属性动作为贯穿伤害，无视防御。",
        "active": true
      },
      {
        "id": "banyue_core_special_buff",
        "name": "核心被动：强化特殊技/支援突击状态",
        "desc": "般岳发动强化特殊技或支援突击时，贯穿力提升300点，造成的火属性伤害提升36%，暴击伤害提升36%，持续30秒。",
        "active": true,
        "crit_dmg": 36.0,
        "dmg_bonus": 36.0,
        "pen_flat": 300.0,
        "tags": [
          "fire",
          "火属性"
        ]
      },
      {
        "id": "banyue_extra_fire_dmg",
        "name": "额外能力：绝巅 (明王状态)",
        "desc": "在怒相状态时消耗山威发动强化特殊技时，般岳会获得一层明王，每层明王会使自身造成的火属性伤害提升5%，最多叠加3层(15%)，持续8秒。",
        "active": true,
        "dmg_bonus": 15.0,
        "tags": [
          "fire",
          "火属性"
        ]
      },
      {
        "id": "banyue_c1_res_shred",
        "name": "影画1：贪欲如火 (战栗状态火属性减抗)",
        "desc": "强化特殊技命中敌人时，使敌人陷入战栗状态，火属性伤害抗性降低10%，持续30秒。",
        "active": true,
        "res_shred": 10.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 1
      },
      {
        "id": "banyue_c2_crit_fire_dmg",
        "name": "影画2：嗔恨如刀 (核心被动增幅)",
        "desc": "核心被动中的暴击伤害增益效果额外提升15%，火属性伤害增益效果额外提升15%。",
        "active": true,
        "crit_dmg": 15.0,
        "dmg_bonus": 15.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 2
      },
      {
        "id": "banyue_c4_dmg",
        "name": "影画4：肃灭单元·零型",
        "desc": "强化特殊技：狮子吼·怒、强化特殊技：山摇·怒、普通攻击：倾山和普通攻击：摧岳造成的伤害提升30%。",
        "active": true,
        "dmg_bonus": 30.0,
        "cinema_req": 4
      },
      {
        "id": "banyue_c6_fire_dmg",
        "name": "影画6：降世明王 (明王额外增伤)",
        "desc": "明王提供的火属性伤害增益效果额外提升8%（共13%/层），持续时间提升至30秒。",
        "active": true,
        "dmg_bonus": 8.0,
        "tags": [
          "fire",
          "火属性"
        ],
        "cinema_req": 6
      }
    ],
    "team_buffs": []
  },
  "1481": {
    "self_buffs": [
      {
        "id": "ryune_core_stun_dmg",
        "name": "核心被动：击破冲浪",
        "desc": "琉音在失衡期间造成的伤害大幅提升，特殊技和连携技有额外加成。",
        "active": true,
        "dmg_bonus": 40.0
      },
      {
        "id": "ryune_extra_impact",
        "name": "额外能力：波浪冲击",
        "desc": "琉音额外能力提升自身冲击力并在特定状态下提升伤害。",
        "active": true,
        "dmg_bonus": 25.0
      },
      {
        "id": "ryune_c2_crit",
        "name": "影画2：冲浪双暴",
        "desc": "琉音影画2提升自身暴击率和暴击伤害。",
        "active": true,
        "crit_rate": 15.0,
        "crit_dmg": 30.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": [
      {
        "id": "ryune_malicious_complaint",
        "name": "特殊技：恶意投诉 (全队增伤)",
        "desc": "发动强化特殊技或连携技后，全队角色造成的伤害提升40%。",
        "active": true,
        "dmg_bonus": 40.0
      }
    ]
  },
  "1491": {
    "self_buffs": [
      {
        "id": "chinatsu_c6_self_state",
        "name": "影画6：潜心创作中！(自身爆发状态)",
        "desc": "进入潜心创作中！状态，自身攻击必定暴击，并根据初始攻击力的0.03%提升暴击伤害（最高105%）。",
        "active": false,
        "crit_rate": 100.0,
        "dynamic_stat": {
          "stat_to_add": "crit_dmg",
          "based_on": "atk",
          "scale": 0.0003,
          "cap": 105.0
        },
        "cinema_req": 6
      }
    ],
    "team_buffs": [
      {
        "id": "chinatsu_core_atk",
        "name": "核心被动：可爱即正义",
        "desc": "处于天使协律状态下角色攻击力提升，提升数值等同于千夏30%初始攻击力，最高不超过1050点 (Rank 7)。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "atk",
          "scale": 0.3,
          "cap": 1050.0
        }
      },
      {
        "id": "chinatsu_extra_vuln",
        "name": "额外能力：白日梦对位法",
        "desc": "处于以太帷幕·妄想重奏内的角色攻击命中敌人时，目标的失衡易伤倍率提升30%，持续40秒。",
        "active": true,
        "stun_vuln": 30.0
      },
      {
        "id": "chinatsu_c1_def_shred",
        "name": "影画1：孤独侵蚀症",
        "desc": "猫的凝视触发并命中敌人时，使目标的防御力降低7%，最多叠加3层 (21%)。",
        "active": true,
        "def_shred": 21.0,
        "cinema_req": 1
      },
      {
        "id": "chinatsu_c2_team_atk",
        "name": "影画2：猫的随波逐流",
        "desc": "千夏处于任意以太帷幕内时，使全队角色攻击力提升10%。",
        "active": true,
        "atk_pct": 10.0,
        "cinema_req": 2
      },
      {
        "id": "chinatsu_c4_dmg_bonus",
        "name": "影画4：妄想调查队",
        "desc": "千夏发动终结技时，使全队角色造成的伤害提升18%，持续60秒。",
        "active": true,
        "dmg_bonus": 18.0,
        "cinema_req": 4
      },
      {
        "id": "chinatsu_c6_gaze_dmg",
        "name": "影画6：空洞大爆炸",
        "desc": "潜心创作中！状态下，全队触发猫的凝视造成的伤害提升50%。",
        "active": true,
        "dmg_bonus": 50.0,
        "tags": [
          "gaze_attack"
        ],
        "cinema_req": 6
      }
    ]
  },
  "1501": {
    "self_buffs": [
      {
        "id": "airei_core_anomaly",
        "name": "核心被动：以太共鸣",
        "desc": "爱芮核心被动提升以太属性异常伤害和异常掌控。",
        "active": true,
        "dmg_bonus": 25.0,
        "tags": [
          "ether",
          "以太"
        ]
      },
      {
        "id": "airei_c2_crit",
        "name": "影画2：共鸣增幅",
        "desc": "爱芮影画2提升自身暴击率和暴击伤害。",
        "active": true,
        "crit_rate": 20.0,
        "crit_dmg": 40.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": [
      {
        "id": "airei_ether_veil",
        "name": "以太帷幕·妄想重奏",
        "desc": "以太帷幕·妄想重奏生效期间，全队角色攻击力额外提升50点，持续30秒。",
        "active": true
      }
    ]
  },
  "1511": {
    "self_buffs": [
      {
        "id": "nangongyu_core_stun",
        "name": "核心被动：以太弓道",
        "desc": "南宫羽在失衡期间造成的以太伤害大幅提升。",
        "active": true,
        "dmg_bonus": 50.0,
        "tags": [
          "ether",
          "以太"
        ]
      },
      {
        "id": "nangongyu_extra_crit",
        "name": "额外能力：气劲穿透",
        "desc": "南宫羽额外能力提升自身暴击率并对敌人施加减抗。",
        "active": true,
        "crit_rate": 20.0,
        "res_shred": 15.0
      },
      {
        "id": "nangongyu_c2_pen",
        "name": "影画2：穿云破雾",
        "desc": "南宫羽影画2提升自身穿透率。",
        "active": true,
        "pen_rate": 20.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": [
      {
        "id": "nangongyu_ether_veil",
        "name": "以太帷幕·妄想重奏",
        "desc": "南宫羽开启以太帷幕·妄想重奏，全队角色攻击力额外提升50点，持续30秒。",
        "active": true
      }
    ]
  },
  "1521": {
    "self_buffs": [
      {
        "id": "xixifu_core_def_ignore",
        "name": "核心被动：能量回复转防御无视",
        "desc": "希希芙自身初始能量自动回复大于140时，每超过1点能量自动回复（实际缩放系数1/12），无视敌人防御力，基础6%，最多提升25%。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "def_shred",
          "based_on": "energy_regen",
          "offset": 140.0,
          "scale": 0.08333,
          "flat": 6.0,
          "cap": 25.0
        }
      },
      {
        "id": "xixifu_extra_dmg",
        "name": "额外能力：雷速冲击",
        "desc": "希希芙额外能力在特定状态下提升电属性伤害。",
        "active": true,
        "dmg_bonus": 30.0,
        "tags": [
          "electric",
          "电属性"
        ]
      },
      {
        "id": "xixifu_c2_crit",
        "name": "影画2：双暴提升",
        "desc": "希希芙影画2提升自身暴击率和暴击伤害。",
        "active": true,
        "crit_rate": 15.0,
        "crit_dmg": 30.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1531": {
    "self_buffs": [
      {
        "id": "starmark_billy_core_pen",
        "name": "核心被动：贯穿神射",
        "desc": "星徽·比利核心被动提供贯穿力加成和物理属性伤害提升。",
        "active": true,
        "pen_flat": 200.0,
        "dmg_bonus": 30.0,
        "tags": [
          "physical",
          "物理"
        ]
      },
      {
        "id": "starmark_billy_extra_crit",
        "name": "额外能力：精准狙击",
        "desc": "星徽·比利额外能力提升自身暴击率。",
        "active": true,
        "crit_rate": 25.0
      },
      {
        "id": "starmark_billy_c2_crit_dmg",
        "name": "影画2：命中爆破",
        "desc": "星徽·比利影画2提升自身暴击伤害。",
        "active": true,
        "crit_dmg": 50.0,
        "cinema_req": 2
      }
    ],
    "team_buffs": []
  },
  "1541": {
    "self_buffs": [
      {
        "id": "promia_core_anomaly",
        "name": "核心被动：盗火 (初始异常掌控转异常精通)",
        "desc": "若普罗米娅的初始异常掌控大于150点，每超过1点初始异常掌控会提升自身1.5点异常精通。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "anomaly_proficiency",
          "based_on": "anomaly_mastery",
          "offset": 150.0,
          "scale": 1.5
        }
      },
      {
        "id": "promia_extra_def_ignore",
        "name": "额外能力：饮冰 (有罪推定异放无视防御)",
        "desc": "普罗米娅发动强化特殊技命中敌人时，敌人获得有罪推定状态，全队角色对有罪推定状态的敌人造成异放效果时无视40%防御力，持续30秒。",
        "active": true,
        "def_ignore": 40.0
      },
      {
        "id": "promia_c1_def_ignore",
        "name": "影画1：理想稚嫩 (异放额外无视防御)",
        "desc": "全队角色对有罪推定状态的敌人造成异放效果时额外无视20%防御力（合计60%）。",
        "active": false,
        "def_ignore": 20.0,
        "cinema_req": 1
      },
      {
        "id": "promia_c2_anomaly",
        "name": "影画2：信念飘摇 (异常精通+异放倍率)",
        "desc": "普罗米娅的异常精通提升40点；消耗霜刑造成的异放效果的倍率提升120%。",
        "active": true,
        "anomaly_proficiency": 40.0,
        "cinema_req": 2
      },
      {
        "id": "promia_c6_res_ignore",
        "name": "影画6：故事未完待续 (异常/紊乱减抗)",
        "desc": "普罗米娅造成的属性异常伤害、紊乱伤害无视敌人15%全属性伤害抗性。",
        "active": true,
        "res_ignore": 15.0,
        "cinema_req": 6
      }
    ],
    "team_buffs": [
      {
        "id": "promia_core_anomaly_dmg",
        "name": "核心被动：盗火 (异放伤害提升)",
        "desc": "若普罗米娅的初始异常掌控大于150点，每超过1点初始异常掌控会提升0.35%全队造成的异放伤害。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "dmg_bonus",
          "based_on": "anomaly_mastery",
          "offset": 150.0,
          "scale": 0.0035
        }
      }
    ]
  },
  "1551": {
    "self_buffs": [
      {
        "id": "peluoisi_extra_crit_dmg",
        "name": "额外能力：强攻状态双暴伤害提升",
        "desc": "佩洛伊斯发动强攻/强化特殊技/连携技/终结技造成的暴击伤害提升35%。",
        "active": true,
        "crit_dmg": 35.0
      }
    ],
    "team_buffs": []
  },
  "1561": {
    "self_buffs": [
      {
        "id": "weilinna_core_dmg",
        "name": "核心被动：风花盈袖",
        "desc": "维琳娜初始能量自动回复大于1.2时，超过部分每超过0.01，造成的伤害提升0.21%，最多提升35%。",
        "active": true,
        "dmg_bonus": 35.0
      },
      {
        "id": "weilinna_extra_anomaly",
        "name": "额外能力：茶会礼仪",
        "desc": "维琳娜造成的风化和乱流伤害提高10%。",
        "active": true,
        "dmg_bonus": 10.0
      },
      {
        "id": "weilinna_c4_atk",
        "name": "影画4：茶话即审判",
        "desc": "维琳娜发动强化特殊技会使自身攻击力提升15%，持续40秒。",
        "active": true,
        "atk_pct": 15.0,
        "tags": [
          "special"
        ],
        "cinema_req": 4
      }
    ],
    "team_buffs": []
  },
  "1571": {
    "self_buffs": [
      {
        "id": "nuomu_core_crit_dmg",
        "name": "核心被动：精准制导 (初始暴击率转爆伤)",
        "desc": "初始暴击率超过50%时，每超过1%，暴击伤害提升1.7%，最多额外提升85%。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "crit_dmg",
          "based_on": "crit_rate",
          "offset": 50.0,
          "scale": 1.7,
          "cap": 85.0
        }
      },
      {
        "id": "nuomu_core_pen_to_atk",
        "name": "核心被动：精准制导 (贯穿力转攻击力)",
        "desc": "诺姆会额外根据自身贯穿力额外提升攻击力，每1点贯穿力将提升1.25点攻击力，最多提升1200点攻击力。",
        "active": true,
        "dynamic_stat": {
          "stat_to_add": "atk_flat",
          "based_on": "pen_flat",
          "scale": 1.25,
          "cap": 1200.0
        }
      }
    ],
    "team_buffs": [
      {
        "id": "nuomu_extra_stun_vuln",
        "name": "额外能力：集群优势 (失衡易伤倍率提升)",
        "desc": "诺姆及其造物攻击命中敌人时，对敌人施加1层技术鸿沟，每层使目标的失衡易伤倍率提升3%，最多叠加10层(30%)。",
        "active": true,
        "stun_vuln": 30.0
      },
      {
        "id": "nuomu_extra_dmg",
        "name": "额外能力：集群优势 (全队伤害提升)",
        "desc": "在技术鸿沟生效期间，全队代理人造成的伤害提升20%。",
        "active": true,
        "dmg_bonus": 20.0
      },
      {
        "id": "nuomu_c1_res_shred",
        "name": "影画1：激进远视主义",
        "desc": "任意招式中的破甲弹头或高爆弹头命中敌人时，使敌人的全属性伤害抗性降低15%，持续15秒。",
        "active": true,
        "res_shred": 15.0,
        "cinema_req": 1
      }
    ]
  }
};
